name: Sync Fork and Create PR

on:
  schedule:
     - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allow manual triggering      

permissions:
  contents: write
  actions: read
  pull-requests: write
  repository-projects: write
  
jobs:
  sync-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full history for accurate merging

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list
          sudo apt update
          sudo apt install gh

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Add upstream remote
        run: git remote add upstream https://github.com/HassanurRasool/test_repo_1.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Create or Checkout sync-upstream_1 Branch
        run: |
          git fetch --all
          if git show-ref --verify --quiet refs/heads/sync-upstream_1; then
            git checkout sync-upstream_1
          elif git ls-remote --heads origin sync-upstream_1 | grep sync-upstream_1; then
            git checkout -b sync-upstream_1 origin/sync-upstream_1
          else
            git checkout -b sync-upstream_1 origin/main
            git push origin sync-upstream_1
          fi

      - name: Sync with upstream
        run: |
          git merge upstream/development --no-ff --commit --allow-unrelated-histories -m "Sync with upstream development branch"
          git push origin sync-upstream_1

      - name: Run tests
        run: python -m unittest discover tests

      - name: Run linter
        run: pylint **/*.py

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_url=$(gh pr create --base main --head sync-upstream_1 --title "Sync with upstream development branch" --body "This PR synchronizes the main branch with the latest changes from the upstream development branch.")
          echo "Created PR: $pr_url"

      - name: Cleanup
        if: always()
        run: |
          git checkout main
          git branch -D sync-upstream_1 || true
          git push origin --delete sync-upstream_1 || true

      - name: Notify on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: Workflow failed! Check the logs for more information.
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
