name: Sync Fork and Create PR

on:
  schedule:
     - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allow manual triggering      

permissions:
  contents: write
  pull-requests: write
  
jobs:
  sync-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full history for accurate merging

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Add upstream remote
        run: git remote add upstream https://github.com/HassanurRasool/test_repo_1.git

      - name: Fetch upstream changes
        run: |
          git fetch upstream
          git fetch origin

      - name: Create or update sync-upstream_1 branch
        run: |
          if git ls-remote --exit-code --heads origin sync-upstream_1; then
            git checkout sync-upstream_1
            git reset --hard origin/sync-upstream_1
          else
            git checkout -b sync-upstream_1 origin/main
          fi
          git merge upstream/development --no-ff --commit --allow-unrelated-histories -m "Sync with upstream development branch"
          git push -u origin sync-upstream_1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sync with upstream development branch
          title: Sync with upstream development branch
          body: This PR synchronizes the main branch with the latest changes from the upstream development branch.
          branch: sync-upstream_1
          base: main

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
